# Generated by Django 5.0.6 on 2024-05-10 09:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='main_page', verbose_name='Изображение')),
                ('advantages_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Приемущества заголовок')),
                ('reviews_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отзывы заголовок')),
            ],
            options={
                'verbose_name': 'Контент страницы "О нас"',
                'verbose_name_plural': 'Контент страницы "О нас"',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Контактная информация',
                'verbose_name_plural': 'Контактная информация',
            },
        ),
        migrations.CreateModel(
            name='DeliveryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Доставка',
            },
        ),
        migrations.CreateModel(
            name='MainPageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-заголовок')),
                ('meta_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-описание')),
                ('meta_image', models.FileField(blank=True, default='assets/icons/LOGO.svg', null=True, upload_to='meta_images')),
                ('title1', models.CharField(max_length=255, verbose_name='Строка 1')),
                ('title2', models.CharField(max_length=255, verbose_name='Строка 2')),
                ('title3', models.CharField(max_length=255, verbose_name='Строка 3')),
                ('content_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок текста')),
                ('content_text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('content_image', models.ImageField(blank=True, default='assets/mainpage/content_image.png', null=True, upload_to='main_page', verbose_name='Изображение')),
                ('bestsellers_tittle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Бестселлеры заголовок')),
                ('discount_tittle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Скидки заголовок')),
                ('all_products_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Все товары заголовок')),
            ],
            options={
                'verbose_name': 'Контент главной страницы',
                'verbose_name_plural': 'Контент главной страницы',
            },
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('additional_text', models.TextField(blank=True, null=True, verbose_name='Дополнительный текст')),
            ],
            options={
                'verbose_name': 'Об оплате',
                'verbose_name_plural': 'Об оплате',
            },
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField(help_text='Оригинальный текст, который отображается на сайте.', max_length=20000, verbose_name='Оригинальный текст')),
                ('current_text', models.TextField(help_text='Измененный или текущий текст, который отображается на сайте.', max_length=20000, verbose_name='Текущий текст')),
            ],
            options={
                'verbose_name': 'Контент сайта',
                'verbose_name_plural': 'Контент сайта',
            },
        ),
        migrations.CreateModel(
            name='WholesalerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('additional_text', models.TextField(blank=True, null=True, verbose_name='Дополнительный текст')),
                ('button_text', models.CharField(max_length=100, verbose_name='Текст кнопки')),
                ('button_link', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Оптовикам',
                'verbose_name_plural': 'Оптовикам',
            },
        ),
        migrations.CreateModel(
            name='AdvantageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content_text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advantages', to='shop.aboutpagemodel')),
            ],
            options={
                'verbose_name': 'Приемущество',
                'verbose_name_plural': 'Приемущества',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('map_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на карту')),
                ('contact_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='shop.contactinfo')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.CreateModel(
            name='MainPageSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide', models.ImageField(upload_to='main_slider')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.mainpagemodel', verbose_name='slides')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слыйды',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('contact_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phones', to='shop.contactinfo')),
            ],
            options={
                'verbose_name': 'Телефон',
                'verbose_name_plural': 'Телефоны',
            },
        ),
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.ImageField(upload_to='reviews', verbose_name='Отзыв')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.aboutpagemodel')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Соцсети')),
                ('logo', models.FileField(blank=True, null=True, upload_to='social_link_logo', verbose_name='Логотип')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('contact_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='social_links', to='shop.contactinfo')),
            ],
            options={
                'verbose_name': 'Соцсеть',
                'verbose_name_plural': 'Соцсети',
            },
        ),
        migrations.CreateModel(
            name='WholesalerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='wholesaler_images')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('wholesaler_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.wholesalerinfo')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, help_text='Дни когда это время актуально (можно оставить пустым)', max_length=255, null=True, verbose_name='Рабочее время')),
                ('start', models.TimeField(default=datetime.time(10, 0))),
                ('end', models.TimeField(default=datetime.time(10, 0))),
                ('contact_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_schedules', to='shop.contactinfo')),
            ],
            options={
                'verbose_name': 'Рабочее время',
                'verbose_name_plural': 'Рабочее время',
            },
        ),
    ]
