# Generated by Django 5.0.6 on 2024-05-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesalerinfo',
            name='title',
            field=models.CharField(default=1, max_length=255, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
