# Generated by Django 5.0.6 on 2024-05-10 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=255, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Продукт')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('price_kgs', models.PositiveIntegerField(verbose_name='Цена в сомах')),
                ('price_kzt', models.PositiveIntegerField(verbose_name='Цена в тенге')),
                ('price_rub', models.PositiveIntegerField(verbose_name='Цена в рублях')),
                ('price_usd', models.PositiveIntegerField(verbose_name='Цена в долларах')),
                ('price_discounted_kgs', models.PositiveIntegerField(blank=True, null=True, verbose_name='Скидочная цена в сомах')),
                ('price_discounted_kzt', models.PositiveIntegerField(blank=True, null=True, verbose_name='Скидочная цена в тенге')),
                ('price_discounted_rub', models.PositiveIntegerField(blank=True, null=True, verbose_name='Скидочная цена в рублях')),
                ('price_discounted_usd', models.PositiveIntegerField(blank=True, null=True, verbose_name='Скидочная цена в долларах')),
                ('is_top', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-заголовок')),
                ('meta_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-описание')),
                ('meta_image', models.FileField(blank=True, default='assets/icons/logo.png', null=True, upload_to='meta_images')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['-is_active'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=255, verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размеры',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255, verbose_name='Тэг')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
            },
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключ')),
                ('value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Значение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='catalog.product', verbose_name='Характеристика')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='catalog.tag', verbose_name='Тэги'),
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
                ('size', models.ManyToManyField(related_name='variants', to='catalog.size', verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Вариант',
                'verbose_name_plural': 'Варианты',
            },
        ),
        migrations.CreateModel(
            name='VariantMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='products_media', verbose_name='Медиа')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='catalog.variant')),
            ],
            options={
                'verbose_name': 'Медиа',
                'verbose_name_plural': 'Медиа',
            },
        ),
    ]
