# Generated by Django 5.0.6 on 2024-05-10 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='telegramsettings',
            options={'verbose_name': 'Telegram', 'verbose_name_plural': 'Telegram'},
        ),
        migrations.AlterModelOptions(
            name='whatsappsettings',
            options={'verbose_name': 'WhatsApp', 'verbose_name_plural': 'WhatsApp'},
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=255, verbose_name='Имя заказчика'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(max_length=20, verbose_name='Телефон заказчика'),
        ),
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.size', verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.variant', verbose_name='Вариант'),
        ),
    ]
